### ISSUE TITLE
Support adjustable theshold for conversion to mono

### ISSUE THREAD

**Issue by fhunleth** [pappersverk/rpi_fb_capture#1]
Currently anything non-zero gets set to on and this looks really bad with some antialiased screens. Might even be nice to see if there's an easy way to support dithering.

**Comment by luisgabrielroldan** [comment]
Hi @fhunleth , Amazing library!

I implemented a simple Floyd-Steinberg dithering for the 1-bpp formats #4.

Let me know what do you think!

Regards

**Comment by fhunleth** [comment]
Closing since this conversion threshold is settable and also since @luisgabrielroldan's dithering support has been merged.
